### ISSUE TITLE
TOC in overview not correctly linked.

### ISSUE THREAD

**Issue by story645** [DHRI-Curriculum/text-analysis#11]
Sorry I don't have time to put in a PR right now, but the part of speech link in the readme links to the conclusion & some of the other to entries might also be out of order (haven't tried those).

**Comment by kallewesterling** [comment]
Thank you @story645 - I will have a look!

**Comment by kallewesterling** [comment]
Tested all of the links and it seems that the pos_tagging.md was the only not linked file so I'll go ahead and close this issue now. Let me know if you find any other problems!

**Comment by kallewesterling** [comment]
(see 57e40c54cdf6abe933f8c1ac8a11643d224e9e1b)
