### ISSUE TITLE
Time 

### ISSUE THREAD

**Issue by lmrhody** [DHRI-Curriculum/text-analysis#17]
Hi Rafa... do you really think it will take 10 hours to work through this workshop? that seems long to me... https://github.com/DHRI-Curriculum/text-analysis/blob/v2.0-rafa-edits/frontmatter.md#estimated-time

**Comment by kallewesterling** [comment]
@lmrhody in our meeting on Friday, we said to leave this section at 10 hours as a placeholder for now. I think we'll need to get back to this when we do some testing.

**Comment by kallewesterling** [comment]
Labeling this `sprint 2` for review before next sprint.
