### ISSUE TITLE
Add discussion questions to theory-to-practice.md

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/text-analysis#18]
Left TBD from sprint 1, see #15.

**Comment by kallewesterling** [comment]
@rafadavis I can't see the changes reflected in the [theory-to-practice.md file synchronized with GitHub](https://github.com/DHRI-Curriculum/text-analysis/blob/v2.0-rafa-edits/theory-to-practice.md) as of right now, so I am marking this with sprint 4, which will be the last push to finalize this content. Feel free to close out this issue if you just haven't synchronized the file with GitHub and I can't see the changes yet. Just trying to get an overview of where we're standing for next sprint.

**Comment by rafadavis** [comment]
Yes, that's exactly it. I'm just finishing working on Kristen's suggestions before I commit as a whole. 
I've been trying to keep one commit per sprint, to make it easier for me to come back if needed.

**Comment by kallewesterling** [comment]
Oh I see—that means that you're unable to preview the lessons.md file though, using the ["preview tool"](https://kallewesterling.pythonanywhere.com/preview) that I made available, right? Just thinking about ways to implement this in the future - and in my documentation...
