### ISSUE TITLE
check and update all links

### ISSUE THREAD

**Issue by rafadavis** [DHRI-Curriculum/text-analysis#19]

**Comment by kallewesterling** [comment]
Not sure what this one means @rafadavis - maybe just for your internal purposes but if you mean URLs, I think that would be great but it could also be something we do programmatically in the ingestion into the database. I'll create an issue in `django-app` for myself.

**Comment by rafadavis** [comment]
Yeah, I did mean all url's. I already found some that are not working, so I'm already working on them. 
I do agree that doing it programmatically is even better.

**Comment by kallewesterling** [comment]
Cool, I'll try to make it happen :)
