### ISSUE TITLE
Making Your Own Corpus: Data Cleaning: error in challenge

### ISSUE THREAD

**Issue by gofilipa** [DHRI-Curriculum/text-analysis#39]
Some inconsistencies with how you name "my_list2":

EITHER 

> my_list2 = [word for word in b_words if word in text1_clean]

should be

> my_list_2 = [word for word in b_words if word in text1_clean]

OR

> my_list == mylist_2

should be

> my_list == my_list2

**Comment by rafadavis** [comment]
Yes, you're right. Thank you!
