### ISSUE TITLE
adding some ethical languag to beginning sections of workshop

### ISSUE THREAD

**Issue by gofilipa** [DHRI-Curriculum/text-analysis#40]
Tagging people that aren't currently working in this repo, but might be interested in contributing to this suggestion.

Below I've typed out some sentences on ethics that could be copy/pasted into relevant sections in order to enhance the workshop. No pressure to actually use it, but I want to offer it just in case.

In summary, I notice that we could add some language in the earlier sections of the workshop that points to the ethics of text analysis. I'm thinking specifically about the transformations (and reductions) we make on text as data. While it's necessary to make these transformations in order for text to be manipulated, it also flattens the complexity of text. This isn't something to be avoided, but something to keep in mind. 

In the "**Text as Data/Corpora**" section: add some more balanced language in the section on looking for gender differences in writing. Phrase it as looking for ways that gender is *constructed*, not discovered or expressed, in writing. Sample text below:

> Keep in mind that, oftentimes our analysis of gender assumes pre-existing gender roles that reproduce gender as a binary system. Some digital humanists have pointed out that, if gender is binary, then the relation between male and female will likely be one of opposition. As [Laura Mandell says](https://dhdebates.gc.cuny.edu/read/untitled-f2acf72c-a469-49d8-be35-67f9ac1e3a60/section/5d9c1b63-7b60-42dd-8cda-bde837f638f4#ch01), the categories of "male" and "female" are socially constructed, and quantitative analysis practitioners should avoid jumping to conclusions about 'male' and 'female' styles of thinking and writing "as if the M/F terms were simple pointers to an unproblematic reality, transparently referential and not discursively constituted."

In the "**Cleaning and Normalizing**" section: temper some of the language about the neutrality and desirability of transforming text. Try to balance it with some points about being aware of how cleaning & normalizing could have ethical implications. You can do this by adding a section at the end called: "A Note on Ethics"

> A Note on Ethics:

> The act of cleaning/normalizing subscribes text to predetermined categories of meaning, forcing meaning into existing "boxes," so to speak. This doesn't mean that we should avoid cleaning or normalizing text, but that we should be aware of how some textual reductions have the potential to affect meaning. How does quantification reinforce differences or stratifications within our data? We have to be careful about the kinds of questions we are asking, and how we might be reproducing some of our assumptions in our inquiry. 

> To read more about ethics and text analysis, see Lauren Klein's "[Distant Reading After Moretti](https://arcade.stanford.edu/blogs/distant-reading-after-moretti)," where she questions, "Instead of first asking what can be modeled—-what phenomena we can track at scale—-we might instead ask: what might be hidden in this corpus?”

Finally, in "**Searching for Words**" section: add a note reminding the participants that we have to be careful about the analyses we draw from our conclusions. This is the section where we compare Melville and Austen (male and female writers). 

> Remember to be aware of the ethical implications for the conclusions that we might draw about our data. What assumptions might we be reifying about these writers?

I welcome all suggestions or concerns about any of the above!

**Comment by rafadavis** [comment]
Great job, thanks!

**Comment by kallewesterling** [comment]
I agree!
