### ISSUE TITLE
Include screenshots for opening the textanalysis.ipynb file, and another for opening a new notebook file

### ISSUE THREAD

**Issue by rafadavis** [DHRI-Curriculum/text-analysis#42]

**Comment by kallewesterling** [comment]
@rafadavis What is the status on this one? Should I relabel this for `sprint 5`?

**Comment by kallewesterling** [comment]
@rafadavis I'll go ahead and relabel it now, just so it stays with us this sprint.

**Comment by kallewesterling** [comment]
Closing here as I believe this issue is completed. (Part of project clean-up =no action required if you are OK with issue closing.)
