### ISSUE TITLE
Revisit learning objectives

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/text-analysis#50]
@rafadavis, just looking over the learning objectives - do you mind looking whether they are all still relevant and correct? There is one that triggered this issue, "Remove stop words from different languages (English, Spanish, Arabic, etc)" which I don't know whether it is actually addressed in the workshop. Made me think: Are all the other ones correct?

**Comment by rafadavis** [comment]
Good catch. I took that of of the objectives, and instead created "a note about languages" in the workshop to talk about using nltk for other languages.
I also went back to the learning objectives and changed a few more things to make it more satisfactory.

**Comment by kallewesterling** [comment]
Thank you @rafadavis !
