### ISSUE TITLE
In positioning.md clear up confusion with correct syntax in writing vs. code

### ISSUE THREAD

**Issue by lmrhody** [DHRI-Curriculum/text-analysis#9]
In [positioning.md](https://github.com/DHRI-Curriculum/text-analysis/blob/master/sections/positioning.md) the text reads as follows: 

> Try this with text2, Sense and Sensibility. Some relevant words are "marriage," "love," "home," "mother," "husband," "sister," and "wife." Pick a few to compare. (You can compare an unlimited number, but it's easier to read a few at a time.)

This could be confusing for someone transitioning from the written grammar, where commas are inside the quotation marks to a Python list, where the commas appear between the items in the list.

**Comment by kallewesterling** [comment]
Suggested and implemented an edit. Feel free to reverse or change as you see fit.
